import assert from 'node:assert/strict';
import {updateKeyboardOwners} from '../browser/keyboard-owners.mjs';
const event = (code, location = 0, repeat = false) => ({code, location, repeat});
const bits = owners => [...owners.values()].reduce((all, owner) => all | owner.bit, 0);
const owners = new Map();
updateKeyboardOwners(owners, event('ShiftLeft', 1), 4, true);
updateKeyboardOwners(owners, event('ShiftRight', 2), 4, true);
updateKeyboardOwners(owners, event('ShiftRight', 0), 4, false);
assert.equal(bits(owners), 4, 'changed-location right release preserves held left Shift');
updateKeyboardOwners(owners, event('Unidentified'), 4, false);
assert.equal(bits(owners), 0, 'unknown-side release retires remaining Shift');
updateKeyboardOwners(owners, event('ShiftLeft'), 4, true);
updateKeyboardOwners(owners, event('ShiftRight'), 4, true);
updateKeyboardOwners(owners, event('Unidentified'), 4, false);
assert.equal(bits(owners), 0, 'ambiguous release must not strand a second modifier owner');
updateKeyboardOwners(owners, event('ArrowUp'), 16, true);
updateKeyboardOwners(owners, event('Numpad8'), 16, true);
updateKeyboardOwners(owners, event('ArrowUp'), 16, false);
assert.equal(bits(owners), 16, 'Arrow and Numpad aliases keep independent ownership');
updateKeyboardOwners(owners, event('Numpad8'), 16, false);
assert.equal(bits(owners), 0);
updateKeyboardOwners(owners, event('Unidentified'), 4, true);
updateKeyboardOwners(owners, event('ShiftLeft', 1), 4, false);
assert.equal(bits(owners), 0, 'UP with better physical identity releases unknown DOWN');
owners.clear();
assert.equal(updateKeyboardOwners(owners, event('ShiftLeft', 1, true), 4, true), false);
assert.equal(bits(owners), 0, 'repeat cannot re-arm cancelled input');
console.log('PASS shared browser key ownership: aliases, modifier sides, ambiguity and cancellation');
